dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash

#addons:
#  apt:
#    packages:
#    - python-pip


notifications:
#  slack:
#    rooms:
#      secure: WsxSWHpkmFuURmX0DflteZXxpwQ/9Jb+uAgQjDROKS+fS/MhowR4foGidK5ipXBWSBsZ0poKVRZsDympPn+Xh56Dl42y8X6fkYhRMLF/ZR2YVO+A9KPjKuqR0xc8VencT7AM4M7KRe4ImQ/BkBqugG4wzLTiQaFbXTuHMYMDI6hJ96jT2Gsnz7ZNP8YQIyOOLLJXWxegBLy0SjWKoHWvNVzBfY578bZmt/hORZuT12bSRtidEIbuoH/I5Mgtl+Ess6UPrvvRa23sHUK5MvL2uyk1NizM9OhvLVqFa7L8UepExVA6XWVuuDLMc5wqaHzpg6kWTcouCaWtYNiO1h3Cob/RhwqyFch5JPXo/FIFkOExhE3oj3aKZLhZDGkk7qVgQ3/NskizQHh6xSztrYvU3ZPq3e+iF/OP4ndms7psc4c2jjrM2oE+tvz9rNOA76aM/Wz3mhMZAPBlFbqRHqRbxVoAJobStIgtx/wlQP5u89jimFIKY7+IEmsAiDsysqeNdAIaDxghaRq5U3n6MbysQFDDPMtCr9o0IDePB5/m4TpUtgYWuqG1ZJAO/8Cpt1UutevAowynqfgzE4+7wRzFwxB8zJ4eU4hf9yfCU0Rr8E5iBDgV3RyYwPLK4nJmi1hr7qw4pZWRS5P8kvoiwu3s3Ijuo/ofzZAxG6ORg47z9es=
  slack: devops-team-otus:lQRjVybicsrNNFLey9JiR03P