global:
  slack_api_url: 'https://hooks.slack.com/services/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'
  smtp_from: 'alert@example.org'
  smtp_smarthost: '192.168.0.1:25'

route:
  receiver: 'slack-notifications'
  routes:
  - match:     
      severity: warning
    continue: true
    receiver: email-notifications

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#denis_lunev'

- name: 'email-notifications'
  email_configs:
  - to: 'hataldir@gmail.com'
