version: '3.3'
services:

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - front_net
      - back_net

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - front_net
      - back_net

  mongodb-exporter:
    image: mongodb-exporter:master
    command: 
      - '--mongodb.uri=mongodb://post_db'
      - '--collect.database'
    networks:
      - back_net

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.16.0
    ports:
      - '9115:9115'
    networks:
      - front_net
      - back_net

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      - back_net

  grafana:
    image: ${USER_NAME}/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    user: "104"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - back_net
      - front_net

  alertmanager:
    image: ${USER_NAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      - back_net

  telegraf:
    image: ${USER_NAME}/telegraf
    environment:
      - HOST_PROC=/host/proc
    ports:
      - 9273:9273
    volumes:
      - '/proc:/host/proc:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - back_net

  stackdriver:
    image: ${USER_NAME}/stackdriver
    environment:
      - STACKDRIVER_EXPORTER_GOOGLE_PROJECT_ID=docker-275212
#      - STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES="compute.googleapis.com/instance/cpu,compute.googleapis.com/instance/disk"
      - STACKDRIVER_EXPORTER_MONITORING_METRICS_TYPE_PREFIXES=compute.googleapis.com/instance
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/docker-cred.json
    ports:
      - 9255:9255
    networks:
      - back_net    

  trickster:
    image: tricksterio/trickster
#    image: ${USER_NAME}/trickster
    environment:
      - TRK_ORIGIN=http://prometheus:9090
      - TRK_ORIGIN_TYPE=prometheus 
      - TRK_LOG_LEVEL=INFO 
      - TRK_PROXY_PORT=8480
      - TRK_METRICS_PORT=8481
    ports:
      - 8480:8480
    networks:
      - back_net

 
volumes:
  prometheus_data:
  grafana_data:

networks:
  front_net:
  back_net:

