{
 "title": "UI_Sevice_Monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Rate of UI HTTP errors",
   "type": "graph",
   "description": "Rate of UI HTTP errors",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP response time 95% procentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket [5m])) by (le))"
    }
   ]
  },
  {
   "title": "UI HTTP requests",
   "type": "graph",
   "description": "UI HTTP requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(ui_request_count[1m])" }
   ]
  }
 ]
}